apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dummy-secrets
  namespace: dummy-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gsm-secret-store
    kind: SecretStore
  target:
    name: dummy-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: dummy/DB_PASSWORD
