apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gsm-secret-store
  namespace: dummy-dev
spec:
  provider:
    gcpsm:
      projectID: plateng-dev-app-wsky
      auth:
        workloadIdentity:
          clusterLocation: us-east4
          clusterName: plateng-dev-gke-01
          serviceAccountRef:
            name: external-secrets-sa
